on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: zeromq-Ada
      - uses: reznikmm/fedora-ada-action@v2
        with:
          spec: zeromq-Ada/packages/zeromq-ada.spec
      - uses: reznikmm/upload-bintray-docker-action@v2
        with:
          username: reznikmm
          repository: matreshka
          package: zeromq-ada
          version: head-fc32
          sourcePath: x86_64/*
          override: 1
          apiKey: ${{secrets.BINTRAY_API_KEY}}