on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: zeromq-Ada
      - uses: reznikmm/fedora-ada-action@v3
        with:
          spec: zeromq-Ada/packages/zeromq-ada.spec
      - name: Upload tar-ball to Bintray
        uses: reznikmm/upload-bintray-action@v3
        with:
          subject: reznikmm
          repository: matreshka
          package: zeromq-ada
          version: head-fc33
          sourcePath: x86_64/*
          override: 1
          username: reznikmm
          apiKey: ${{secrets.BINTRAY_API_KEY}}
